### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yawlhoo** [snapcrafters/get-iplayer#12]
### What happened?

get_iplayer complains on launch:

INFO: Indexing radio programmes (concurrent)
Can't locate object method "delay" via package "Mojo::IOLoop" at /usr/bin/get_iplayer line 7113.

### What should have happened?

Fetch a program

### Output of `snap info $snap_name`

```shell
name:      get-iplayer
summary:   CLI for downloading content from BBC iplayer
publisher: Snapcrafters
store-url: https://snapcraft.io/get-iplayer
contact:   https://github.com/snapcrafters/get-iplayer/issues
license:   unset
description: |
  Command Line tool for downloading tv and radio programmes from the last 30 days from the BBC
  iPlayer.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - get-iplayer
  - get-iplayer.get-iplayer-cgi
snap-id:      KFpiyRyf3GYcvw8yWZzqf3WLhd0yADIM
tracking:     latest/stable
refresh-date: yesterday at 17:00 PDT
channels:
  latest/stable:    3.30 2022-05-30 (436) 101MB -
  latest/candidate: ↑                           
  latest/beta:      3.30 2022-05-30 (436) 101MB -
  latest/edge:      3.30 2022-05-29 (436) 101MB -
installed:          3.30            (436) 101MB -
```

### Output of `snap connections $snap_name`

```shell
Interface        Plug                         Slot           Notes
home             get-iplayer:home             :home          -
network          get-iplayer:network          :network       -
network-bind     get-iplayer:network-bind     :network-bind  -
opengl           get-iplayer:opengl           :opengl        -
removable-media  get-iplayer:removable-media  -              -
```

### Output of `snap version`

```shell
snap    2.56.2+22.04ubuntu1
snapd   2.56.2+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.4.0-29-generic
```

### Relevant log output

```shell
[112525.901452] audit: type=1400 audit(1660779555.656:58): apparmor="DENIED" operation="capable" profile="/usr/lib/snapd/snap-confine" pid=23880 comm="snap-confine" capability=12  capname="net_admin"
```

### Teminal output of app

```shell
get_iplayer v3.22, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.



INFO: Indexing radio programmes (concurrent)
Can't locate object method "delay" via package "Mojo::IOLoop" at /usr/bin/get_iplayer line 7113.
```

**Comment by diddledani** [comment]
I think you might have multiple copies of get-iplayer installed. Your error message indicates you are running /usr/bin/get_iplayer - this isn't provided in the snap package. To ensure you're getting this error from the snap release, can you please run either `/snap/bin/get-iplayer` (there is an alias to `/snap/bin/get_iplayer` as well so that will also work) or `snap run get-iplayer`

**Comment by yawlhoo** [comment]
I get:

$ /snap/bin/get-iplayer
cannot attach cgroup program: Operation not permitted
$ snap run get-iplayer
cannot attach cgroup program: Operation not permitted

**Comment by diddledani** [comment]
Can you run any snap packages at all? A reboot might clear the issue with cgroups, which is unrelated to any specific snap. If you still have issues with the cgroups message then please post a message to the [Snapcraft Forum](https://forum.snapcraft.io/) tagged in the "snapd" category.

**Comment by yawlhoo** [comment]
I installed a sample snap called "fast." It seems to work:

$ fast
 -> 877.08 Mbps

Other than get-iplayer I have very few snaps.

**Comment by popey** [comment]
This doesn't seem like a bug in the get-iplayer snap itself, but elsewhere. The snap itself works fine, but looks like some environmental issue on the user machine.
