### ISSUE TITLE
get-iplayer for Raspbian snap does not work

### ISSUE THREAD

**Issue by johnaaronrose** [snapcrafters/get-iplayer#9]
I installed get-iplayer on my RaspberryPi (under Raspbian Buster) using instructions from the snapcraft.io/install/get-iplayer/debian 2: it installed OK using snap (get-iplayer from snapcrafters installed).However, it won’t run:
get-iplayer -> bash: get-iplayer: command not found
I checked if it was installed using Synaptic Package Manager and it wasn’t!

**Comment by popey** [comment]
You may need to logout / login again or reboot for your path to be set. Alternatively, what if you run `/snap/bin/get-iplayer`?

**Comment by johnaaronrose** [comment]
logout/login (or rebooting) didn't help. /snap/bin/get-iplayer worked OK. get-iplayer snap creation needs to be redone properly.

**Comment by popey** [comment]
Having tested this again, the snap is working fine on a raspberry pi here. Looks like the path is not set correctly for the user.
